version: '3.7'
services:
  backend:
    restart: always
    build:
      context: '.'
      dockerfile: "Dockerfile"
    image: "uploader:prod"
    ports:
      - "3000:3000"
    environment:
      APP_SOCKET: "0.0.0.0:3000"
      APP_STORAGE: "/storage"
      WEB_ROOT: "/testpage"
    volumes:
      - type: volume
        source: storage
        target: "/storage"

volumes:
  storage:
