   FROM rust:buster AS builder
WORKDIR /app
    RUN apt-get update && apt-get install -y llvm-dev libclang-dev clang
    RUN rustup install nightly && rustup override set nightly
    RUN git clone https://github.com/nothings/stb /usr/local/include/stb

 VOLUME ["/app", "/target", "/usr/local/cargo/registry"]
    RUN cargo install --root /usr/local/cargo cargo-watch
 EXPOSE 3000
    CMD cargo watch -c -x "run --target-dir /target" --poll

# vim: set ft=dockerfile
